[package]
name = "iroh-gossip-discovery"
version = "0.6.1"
edition = "2024"
license = "MPL-2.0"
description = "Discover iroh nodes via iroh-gossip"
homepage = "https://github.com/therishidesai/iroh-gossip-discovery"
repository = "https://github.com/therishidesai/iroh-gossip-discovery"
readme = "README.md"

[dependencies]
bytes = "1.10.1"
dashmap = "6.1.0"

ed25519-dalek = "3.0.0-pre.6"

rand = "0.9.2"
futures = "0.3"

iroh = { version = "0.98.1", features = ["address-lookup-mdns", "tls-ring"] }
iroh-gossip = "0.98.0"
iroh-base = "0.98.0"
iroh-dns-server = "0.98.1"

rustls = { version = "0.23.33", default-features = false }

postcard = { version = "1.0", features = ["alloc"] }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[example]]
name = "address_book_demo"
path = "examples/address_book_demo.rs"
